version: '3.8'

services:

  web-app:
    restart: always
    build:
      context: .
    ports:
      - "7115:7115"
    volumes:
      - .:/app
    command: gunicorn config.wsgi:application --bind 0.0.0.0:7115 --workers 4
#    command: python manage.py runserver 0.0.0.0:8000
