# Generated by Django 5.0.2 on 2024-02-25 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Exercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
                ('video', models.URLField(blank=True, null=True)),
            ],
            options={
                'verbose_name': 'Вправа',
                'verbose_name_plural': 'Вправи',
                'ordering': ['name'],
            },
        ),
        migrations.CreateModel(
            name='DayExercise',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(auto_now_add=True)),
                ('exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jum_app.exercise')),
            ],
            options={
                'verbose_name': 'Впава на день',
                'verbose_name_plural': 'Вправи на день',
                'ordering': ['date', 'exercise'],
            },
        ),
        migrations.CreateModel(
            name='MuscleTypes',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=255, unique=True)),
            ],
            options={
                'verbose_name': "День груп м'язів",
                'verbose_name_plural': "Дні груп м'язів",
                'ordering': ['name'],
                'indexes': [models.Index(fields=['id', 'name'], name='jum_app_mus_id_651db5_idx'), models.Index(fields=['id'], name='jum_app_mus_id_93857d_idx'), models.Index(fields=['name'], name='jum_app_mus_name_494e58_idx')],
            },
        ),
        migrations.AddField(
            model_name='exercise',
            name='muscle_type',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jum_app.muscletypes'),
        ),
        migrations.CreateModel(
            name='Repeat',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('approach', models.PositiveIntegerField()),
                ('repeats', models.PositiveIntegerField()),
                ('day_exercise', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='jum_app.dayexercise')),
            ],
            options={
                'verbose_name': 'Впава на день',
                'verbose_name_plural': 'Вправи на день',
                'ordering': ['day_exercise', 'approach', 'repeats'],
            },
        ),
        migrations.AddIndex(
            model_name='dayexercise',
            index=models.Index(fields=['id', 'date', 'exercise'], name='jum_app_day_id_43cb0e_idx'),
        ),
        migrations.AddIndex(
            model_name='dayexercise',
            index=models.Index(fields=['id'], name='jum_app_day_id_df6449_idx'),
        ),
        migrations.AddIndex(
            model_name='dayexercise',
            index=models.Index(fields=['date'], name='jum_app_day_date_573002_idx'),
        ),
        migrations.AddIndex(
            model_name='dayexercise',
            index=models.Index(fields=['exercise'], name='jum_app_day_exercis_bad233_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['id', 'name', 'muscle_type'], name='jum_app_exe_id_c70cb5_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['id'], name='jum_app_exe_id_0b72fe_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['name'], name='jum_app_exe_name_b2b3bc_idx'),
        ),
        migrations.AddIndex(
            model_name='exercise',
            index=models.Index(fields=['muscle_type'], name='jum_app_exe_muscle__3c238b_idx'),
        ),
        migrations.AddIndex(
            model_name='repeat',
            index=models.Index(fields=['id', 'day_exercise', 'approach', 'repeats'], name='jum_app_rep_id_5a1910_idx'),
        ),
        migrations.AddIndex(
            model_name='repeat',
            index=models.Index(fields=['id'], name='jum_app_rep_id_4fe55b_idx'),
        ),
        migrations.AddIndex(
            model_name='repeat',
            index=models.Index(fields=['day_exercise'], name='jum_app_rep_day_exe_659571_idx'),
        ),
        migrations.AddIndex(
            model_name='repeat',
            index=models.Index(fields=['approach'], name='jum_app_rep_approac_32584f_idx'),
        ),
        migrations.AddIndex(
            model_name='repeat',
            index=models.Index(fields=['repeats'], name='jum_app_rep_repeats_4bb17f_idx'),
        ),
    ]
