# Generated by Django 5.0.2 on 2024-02-25 19:04

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jum_app', '0002_alter_repeat_options_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='repeat',
            options={'ordering': ['day_exercise', 'repeats'], 'verbose_name': 'Підхід', 'verbose_name_plural': 'Підходи'},
        ),
        migrations.AddField(
            model_name='repeat',
            name='weight',
            field=models.FloatField(default=7.5),
            preserve_default=False,
        ),
    ]
