# Generated by Django 5.0.2 on 2024-02-25 19:18

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jum_app', '0003_alter_repeat_options_repeat_weight'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='hurd_type',
            field=models.CharField(choices=[('Отказ', 'Отказ'), ('Дуже складно', 'Дуже складно'), ('Ідеально', 'Ідеально'), ('Задегко', 'Задегко')], default='Ідеально', max_length=255),
            preserve_default=False,
        ),
    ]
