# Generated by Django 5.0.2 on 2024-04-11 13:24

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('jum_app', '0005_alter_dayexercise_options_alter_repeat_options_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='repeat',
            name='in_kg',
            field=models.FloatField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='repeat',
            name='in_lb',
            field=models.FloatField(blank=True, null=True),
        ),
    ]
